[package]
name = "mc-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-launcher-api = { path = "./mc-launcher-api/" }

chrono = { version = "0.4", features = ["serde"] }

reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
